base_model: /app/models/Ministral-3-14B-Reasoning-2512
flash_attention: true
use_kernels: false
model_kwargs:
  attn_implementation: "flash_attention_2"

# keep everything in VRAM, not a discrete GPU system
# XXX JB
#experimental_skip_move_to_device: true
experimental_skip_move_to_device: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

# XXX JB don't bother with the validation loss calculation for now
#val_set_size: 2000
val_set_size: 0
output_dir: /app/models/ministral-3-14b-cpt-science

sequence_len: 2048
pad_to_sequence_len: true
#sample_packing_bin_size: 2048
sample_packing: false
eval_sample_packing: false
pretrain_multipack_attn: false

# batch size math: 4 * 4 * 4 (GPUs) = 64 global batch
micro_batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 3
max_steps: 100

optimizer: adamw_torch
lr_scheduler: constant_with_warmup
learning_rate: 2e-5

bf16: true
tf32: false

save_strategy: "epoch"
logging_steps: 1
warmup_ratio: 0.03

deepspeed:
  bf16:
    enabled: true
  gradient_accumulation_steps: "auto"
  gradient_clipping: "auto"
  optimizer:
    params:
      adam_w_mode: true
      torch_adam: true
    type: AdamW
  steps_per_print: 1
  train_batch_size: "auto"
  train_micro_batch_size_per_gpu: "auto"
  wall_clock_breakdown: false
  zero_optimization:
    contiguous_gradients: true
    gather_16bit_weights_on_model_save: true
    memory_efficient_linear: false
    overlap_comm: false
    reduce_bucket_size: 50000000
    stage: 3
    stage3_max_live_parameters: 1000000000
    stage3_max_reuse_distance: 1000000000
    stage3_param_persistence_threshold: 1000000
    stage3_prefetch_bucket_size: 50000000
    sub_group_size: 50000000

save_safetensors: true
ray_log_to_driver: false

streaming: false
streaming_multipack_buffer_size: 2000
skip_prepare_dataset: true


#####################################################################################
# zenith autogenerated settings follow: data prep path, ray resource settings
#####################################################################################


