base_model: /app/models/Mistral-Small-4-119B-2603
flash_attention: true
use_kernels: false
model_kwargs:
  attn_implementation: "flash_attention_2"

# prevent oom by not putting model to GPU before sharding
experimental_skip_move_to_device: true

# gradient checkpointing is mandatory for 119B on 4-8 GPUs
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false

datasets:
  - path: /app/datasets/SFT_HEDP_dataset/hedp_dataset.jsonl
    type: chat_template
    chat_template: tokenizer_default
    field_messages: conversations
    message_property_mappings:
      content: value
      role: from
    roles:
      user: ["human"]
      assistant: ["gpt"]

val_set_size: 0
output_dir: /app/models/mistral-small-4-119B-hedp

# sequence length for MoE models impacts HBM significantly
sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

dataset_num_proc: 128
dataloader_num_workers: 2

# total batch size = micro_batch (4) * grad_accum (4) * GPUs
# On 2 nodes (8 GPUs) = 128
# On 4 nodes (16 GPUs) = 256
micro_batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 100
max_steps: 50

optimizer: adamw_torch
lr_scheduler: constant_with_warmup
learning_rate: 2e-5

bf16: true
tf32: false

activation_offloading: false

logging_steps: 1
saves_per_epoch: 1

warmup_ratio: 0.03

# deepSpeed ZeRO-3 is required for 119B
deepspeed: /app/mistral-small-4-119B-fft-hedp.zero3.json

save_safetensors: true
ray_log_to_driver: false

#####################################################################################
# zenith autogenerated settings follow: data prep path, ray resource settings
#####################################################################################

