-- @MODULE_NAME@/@VERSION@
-- Self-contained nightly ROCm + PyTorch virtual environment (GPU arch @GPU_ARCH@).
-- Generated by install_rocm_pytorch.sh from this template; @VENV@ / @DEVEL@ are
-- substituted with the absolute paths resolved after the venv is built.
--
-- Loading this module reproduces the upstream setup_rocm.sh environment without
-- needing to `source .../bin/activate`: it puts the venv (and the extracted
-- ROCm SDK) on PATH/LD_LIBRARY_PATH and exports the ROCm/HIP variables.

whatis("Nightly ROCm + PyTorch venv (arch @GPU_ARCH@), self-contained pip install")
help([[
Nightly ROCm + PyTorch venv built by install_rocm_pytorch.sh.
Provides: python3 (venv), torch/torchvision (ROCm), rocprofv3, rocprof-compute,
rocprof-sys, and the ROCm SDK. Load, then run the PyTorch_Profiling scripts.
]])

-- Only one ROCm-providing environment should be loaded at a time.
family("rocm")

local venv  = "@VENV@"
local devel = "@DEVEL@"

-- Virtualenv activation, expressed as env vars (no activate script needed).
setenv("VIRTUAL_ENV", venv)
prepend_path("PATH", pathJoin(venv, "bin"))
setenv("PYTHONNOUSERSITE", "1")

-- Extracted ROCm SDK (from `rocm-sdk init`).
setenv("ROCM_PATH", devel)
setenv("HIP_PATH", devel)
setenv("HIP_DEVICE_LIB_PATH", pathJoin(devel, "lib/llvm/amdgcn/bitcode"))
prepend_path("PATH", pathJoin(devel, "bin"))
prepend_path("LD_LIBRARY_PATH", pathJoin(devel, "lib"))
prepend_path("LD_LIBRARY_PATH", pathJoin(devel, "lib/rocm_sysdeps/lib"))
